meta_data:
  version: "1.0"
  description: "Base config file for training RotNet self supervised classifier model using a selected directory of images"

defaults: 
  model_name: &model_name dual_mask_multi_task
  step: &step 200
  num_rotations: &num_rotations 4
  seed: &seed 42

loops:
  device: "cuda:1"
  grad_acc: [1, 1]
  start: 0
  end: 230
  seed: *seed

logs:
  model_name: *model_name
  logger_type: basic
  print_freq: 10
  iter_init: 0
  best_init: [.inf, 0]
  step: *step
  exp_dir: "dualmask_masked_awl_89_230" 
  sub_dir: "model_0"
  last_title: last_model.pth
  best_post_title: post_best.pth
  best_pre_title: pre_best.pth

model:
  model_name: *model_name
  load_model: true
  params:
    backbone_type: pre-trained
    drop_out: 0.5
    batch_norm: false
    trainable_layers: 5
    num_classes: 2
    hidden_layers: 256
    min_size: 800
    max_size: 1333
    load_path: outputs/models/dual_mask_data_multi_awl/model_0/pre_best.pth

dataset:
  source: [data_handling/sources/jersey_dataset_v4, data_handling/sources/pseudo_labels]
  random_seed: *seed
  model_name: *model_name
  col_fn: true
  params:
    train:
      dir: [train, null]
      json: [train.json, train_v2.json]
      batch_size: [1, 1]
      shuffle: true
      num_workers: 0
      augmentations: true
    val:
      dir: [val, null]
      json: [val.json, val_v2.json]
      batch_size: [1, 1]
      shuffle: false
      num_workers: 0
      augmentations: false
    test:
      dir: [test, null]
      json: [test.json, test_v2.json]
      batch_size: [1, 1]
      shuffle: false
      num_workers: 0
      augmentations: false

losses:
  model_name: *model_name
  params: 
    awl: true

optimiser:
  model_name: *model_name
  opt_name: "Adam"
  opt_params:
    lr: 0.00005 
  sched_name: "StepLR"
  sched_params:
    step: *step
    gamma: 0.1
