meta_data:
  version: "1.0"
  description: "Base config file for training RotNet self supervised classifier model using a selected directory of images"

defaults: 
  model_name: &model_name jigmask_multi_task
  step: &step 100
  num_tiles: &num_tiles 9
  num_permutations: &num_permutations 100
  seed: &seed 42

loops:
  device: "cuda:0"
  grad_acc: [1, 1]
  start: 0
  end: 130
  seed: *seed

logs:
  model_name: *model_name
  logger_type: basic
  print_freq: 10
  iter_init: 0
  best_init: [.inf, 0]
  step: *step
  exp_dir: "JIGMASK_DEV" 
  sub_dir: "model_0"
  last_title: last_model.pth
  best_post_title: post_best.pth
  best_pre_title: pre_best.pth

model:
  model_name: *model_name
  load_model: false
  params:
    backbone_type: pre-trained
    num_tiles: *num_tiles
    num_permutations: *num_permutations
    drop_out: 0.5
    batch_norm: false
    trainable_layers: 5
    num_classes: 2
    hidden_layers: 256
    min_size: 800
    max_size: 1333

dataset:
  source: [data_handling/sources/jersey_dataset_v4, data_handling/sources/All_RGB]
  random_seed: *seed
  model_name: *model_name
  sub_mod_name: jigmask_resnet_50
  col_fn: true
  params:
    num_tiles: *num_tiles
    num_permutations: *num_permutations
    buffer: false
    split:
      train_test: 0.8
      train_val: 0.8
    train:
      dir: train
      json: train.json
      batch_size: [1, 4]
      shuffle: true
      num_workers: 0
      augmentations: false
    val:
      dir: val
      json: val.json
      batch_size: [1, 1]
      shuffle: false
      num_workers: 0
      augmentations: false
    test:
      dir: test
      json: test.json
      batch_size: [1, 1]
      shuffle: false
      num_workers: 0
      augmentations: false

losses:
  model_name: *model_name
  params: []

optimiser:
  model_name: *model_name
  opt_name: "Adam"
  opt_params:
    lr: 0.000000005 
  sched_name: "StepLR"
  sched_params:
    step: *step
    gamma: 0.1