meta data:
  version: "1.0"
  desctiption: "Base config file for training RotNet self supervised classifier model using a selected directory of images"

defaults: 
  model_name: &model_name jigsaw
  step: &step 50
  seed: &seed 42
  num_tiles: &num_tiles 9
  num_permutations: &num_permutations 100

loops:
  device: "cuda:0"
  grad_acc: null
  start: 0
  end: 50
  seed: *seed

logs:
  model_name: *model_name
  logger_type: basic
  print_freq: 20
  iter_init: 0
  best_init: .inf
  step: *step
  exp_dir: "Jigsaw/bs16_run0" 
  sub_dir: "model_0"
  last_title: last_model.pth
  best_post_title: post_best.pth
  best_pre_title: pre_best.path

model:
  model_name: *model_name
  load_model: false
  params:
    backbone_type: pre-trained
    num_tiles: *num_tiles
    num_permutations: *num_permutations
    batch_norm: false
    trainable_layers: 5

dataset:
    model_name: *model_name
    source: data_handling/sources/All_RGB
    random_seed: *seed
    col_fn: null
    params:
      col_fn: null
      num_tiles: *num_tiles
      num_permutations: *num_permutations
      buffer: true
      split:
        train_test: 0.8
        train_val: 0.8
      train:
        batch_size: 16
        shuffle: true
        num_workers: 0
        augmentations: true
      val:
        batch_size: 1
        shuffle: false
        num_workers: 0
        augmentations: false
      test:
        batch_size: 1
        shuffle: false
        num_workers: 0
        augmentations: false

losses:
  model_name: *model_name
  params: []

optimiser:
  model_name: *model_name
  opt_name: "Adam"
  opt_params:
    lr: 0.00005 
  sched_name: "StepLR"
  sched_params:
    step: *step
    gamma: 0.1
